spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/historyrecord
    username: Eillen_Tom
    password: 1944563409

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 8181
  tomcat:
    max-http-header-size: 10485760 # 设置为 128 KB
    max-http-form-post-size: 10485760 # 默认是 10 MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  mapper-locations: classpath:mappers/*xml

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: Your accessKeyId
    accessKeySecret: Your AccessKeySecret
    bucketName: Your bucketName

# Spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
